### ISSUE TITLE
version 8.2.0 did not work with typescript (3.7.5) node version 13.9.0

### ISSUE THREAD

**Issue by AZchVVT** [apache/couchdb-nano#209]
Errors:

node_modules/nano/lib/nano.d.ts(48,5): error TS7010: 'followUpdates', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(49,5): error TS7010: 'followUpdates', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(54,5): error TS7010: 'follow', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(69,16): error TS7006: Parameter 'source' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(69,24): error TS7006: Parameter 'target' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(69,32): error TS7006: Parameter 'opts0' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(69,39): error TS7006: Parameter 'callback0' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(70,17): error TS7006: Parameter 'id' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(70,21): error TS7006: Parameter 'rev' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(70,26): error TS7006: Parameter 'opts0' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(70,33): error TS7006: Parameter 'callback0' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(71,15): error TS7006: Parameter 'id' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(71,19): error TS7006: Parameter 'opts0' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(71,26): error TS7006: Parameter 'callback0' implicitly has an 'any' type.
node_modules/nano/lib/nano.d.ts(108,5): error TS7010: 'follow', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(110,5): error TS7010: 'followUpdates', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(111,5): error TS7010: 'followUpdates', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(140,5): error TS7010: 'follow', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/nano/lib/nano.d.ts(141,5): error TS7010: 'follow', which lacks return-type annotation, implicitly has an 'any' return type.

**Comment by glynnbird** [comment]
The Nano TypeScript definitions are now tested and show no errors on various versions of Node we test agains. However, your logs show reasonable errors which could be corrected. Can you specify how you  errors?

**Comment by fox1t** [comment]
Hi there. We have same errors on our build since 8.2.0
`typescript: "~3.8.2"`
`node: "12.16.1"`
This is the repo: 
https://github.com/HospitalRun/hospitalrun-server
and this is the failing build:

**Comment by glynnbird** [comment]
I see the errors @fox1t , but how can I reproduce them on my machine or on Travis. If I do `tsc lib/nano.d.ts` I get no errors?

**Comment by glynnbird** [comment]
oooh `tsc --strict....` seems to do the trick....

**Comment by fox1t** [comment]
Unfortunately TS compiler checks also dependencies typings. Is it feasible to add the missing types?

**Comment by brandonpsmith** [comment]
you can use the --skipLibCheck flag in your ts compiler options. i hope this get's fixed so i can use strict and not have to skip the lib check. WARNING: this skips all declaration files (*.d.ts)

**Comment by glynnbird** [comment]
@fox1t @brandonpsmith this is fixed and waiting review + release

**Comment by brandonpsmith** [comment]
@glynnbird thank you for the quick work

**Comment by glynnbird** [comment]
Fixed in 8.2.1

**Comment by fox1t** [comment]
@glynnbird Thanks for your celerity!
